ALTER TABLE cra.timesheets
  ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS rejected_by UUID,
  ADD COLUMN IF NOT EXISTS reject_reason TEXT NOT NULL DEFAULT '';

ALTER TABLE cra.time_lines
  ADD COLUMN IF NOT EXISTS billable BOOLEAN NOT NULL DEFAULT TRUE;
