ALTER TABLE org.societes
    ADD COLUMN IF NOT EXISTS adresse TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS siret TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS url_tenant TEXT NOT NULL DEFAULT '';
