ALTER TABLE org.societes
    ADD COLUMN IF NOT EXISTS adresse_numero TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS adresse_boite TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS code_postal TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS ville TEXT NOT NULL DEFAULT '';
