ALTER TABLE org.clients
    ADD COLUMN IF NOT EXISTS pays TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS adresse TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS adresse_numero TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS adresse_boite TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS code_postal TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS ville TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS siret TEXT NOT NULL DEFAULT '';
