-- Moved: canonical script is internal/platform/db/grants_kore_app.sql
-- Applied automatically by `kore-api migrate` (Cloud Run job kore-migrate).
-- Manual / setup-gcp: ./infra/gcp/apply-db-grants.sh
