-- Privileges for kore_app (idempotent). Run as kore_migrate / owner after migrations.
-- ETT: audit_journal is append-only (SELECT+INSERT only).

-- Schema USAGE
GRANT USAGE ON SCHEMA public TO kore_app;
GRANT USAGE ON SCHEMA platform TO kore_app;
GRANT USAGE ON SCHEMA org TO kore_app;
GRANT USAGE ON SCHEMA cra TO kore_app;
GRANT USAGE ON SCHEMA conges TO kore_app;
GRANT USAGE ON SCHEMA budget TO kore_app;
GRANT USAGE ON SCHEMA tma TO kore_app;
GRANT USAGE ON SCHEMA billing TO kore_app;
GRANT USAGE ON SCHEMA workflow TO kore_app;
GRANT USAGE ON SCHEMA notifications TO kore_app;
GRANT USAGE ON SCHEMA publicsite TO kore_app;
GRANT USAGE ON SCHEMA ai TO kore_app;
GRANT USAGE ON SCHEMA ssii TO kore_app;
GRANT USAGE ON SCHEMA support TO kore_app;
GRANT USAGE ON SCHEMA maintenance TO kore_app;
GRANT USAGE ON SCHEMA invoicing TO kore_app;
GRANT USAGE ON SCHEMA ett TO kore_app;
GRANT USAGE ON SCHEMA reporting TO kore_app;
GRANT USAGE ON SCHEMA admin TO kore_app;
GRANT USAGE ON SCHEMA integrations TO kore_app;

-- Full CRUD schemas
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO kore_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA platform TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA platform TO kore_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA org TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA org TO kore_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA cra TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA cra TO kore_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA conges TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA conges TO kore_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA budget TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA budget TO kore_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA tma TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA tma TO kore_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA billing TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA billing TO kore_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA workflow TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA workflow TO kore_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA notifications TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA notifications TO kore_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA publicsite TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA publicsite TO kore_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ai TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ai TO kore_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ssii TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ssii TO kore_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA support TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA support TO kore_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA maintenance TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA maintenance TO kore_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA invoicing TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA invoicing TO kore_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA reporting TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA reporting TO kore_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA admin TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA admin TO kore_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA integrations TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA integrations TO kore_app;

-- ETT: CRUD on operational tables; audit_journal append-only
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ett TO kore_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ett TO kore_app;
REVOKE UPDATE, DELETE ON TABLE ett.audit_journal FROM kore_app;

-- Default privileges for future objects created by kore_migrate
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA platform GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA org GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA cra GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA conges GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA budget GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA tma GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA billing GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA workflow GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA notifications GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA publicsite GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA ai GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA ssii GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA support GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA maintenance GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA invoicing GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA ett GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA reporting GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA admin GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA integrations GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kore_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA platform GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA org GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA cra GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA conges GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA budget GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA tma GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA billing GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA workflow GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA notifications GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA publicsite GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA ai GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA ssii GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA support GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA maintenance GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA invoicing GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA ett GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA reporting GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA admin GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA integrations GRANT USAGE, SELECT ON SEQUENCES TO kore_app;
